# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install r-cran-rjags

language: R
sudo: false
cache: packages
